- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      # state: present
      state: absent
    loop:
    - mysql
    - nginx
    - zip